### ISSUE TITLE
Typed Arrays of value types are serialized incorrectly when they are the root object.

### ISSUE THREAD

**Issue by rbeurskens** [mgholam/fastBinaryJSON#10]
When serializing typed arrays of a value type when it is the root object, 'native' types result in `object[]` and complex structs result in `List<object>` when deserializing them back.

Commenting the following line seems to help, through I don't know why this conditional is even there.:
```C#
internal sealed class BJSONSerializer : IDisposable
{
        private void WriteTypedArray(ICollection array)
        {
            bool pendingSeperator = false;
            bool token = true;
            var t = array.GetType();
            if (t != null) // non generic array
            {
                if (t.GetElementType().IsClass)  // <= removing this line seems to get it working
                {
```
EDIT typo

**Comment by mgholam** [comment]
Silly me! :)

I removed the line and all the test pass...

Thanks.

**Comment by rbeurskens** [comment]
by the way ... `array.GetType()` will never be `null` in the above code. (it will also throw if a `null` reference is passed)
Not sure about the intent of the `if (t != null)` check

**Comment by mgholam** [comment]
fixed thanks!
