### ISSUE TITLE
Failed to parse when root type is enum type.

### ISSUE THREAD

**Issue by al6uiz** [mgholam/fastBinaryJSON#6]
`var myEnumValue = (MyEnum)BJSON.ToObject(rawData, typeof(MyEnum));`

I expected to be returned enum value, but it returns string.

Need to add the following line to  BJSON.cs : 314

`
  if (type?.IsEnum == true)  return CreateEnum(type, o);`

**Comment by mgholam** [comment]
Thanks!

**Comment by mgholam** [comment]
Added to `v1.4.23`
